### ISSUE TITLE
Password history

### ISSUE THREAD

**Issue by CrispinF** [joeaudette/cloudscribe#1]
In a security review of a solution based on mojoPortal, a client wanted settings to prevent users' password changes using a password that had been used before (within N changes). This was the only issue we failed on. Perhaps you could put a password history option onto the roadmap for cloudscribe?
I think it could be a site setting as simple as "Allow re-use of a previous password when changing password?" yes/no, plus a table containing the previous pwds for each user? If set to "no" this would allow a site to pass all box-tick exercises.
Apologies if an "issue" is not the right place to log this request - suggestions?

**Comment by joeaudette** [comment]
I have decided not to implement this in cloudscribe core as discussed in [issue 219](https://github.com/joeaudette/cloudscribe/issues/219)

See that issue for further explanation, this feature could be implemented separate from cloudscribe core
