### ISSUE TITLE
Page to manage tenants

### ISSUE THREAD

**Issue by papyr** [joeaudette/cloudscribe#107]
Hi, it would be nice to have a page 

- Manage Add/Delete tenants
- Impersonate a user role to test
- SMS/Text based authentication and lockout/unlock out
- User login activity audit

This page has some [samples](http://bit.ly/2h2nUuO)/demo to show - [source](https://github.com/aspnetboilerplate/module-zero/tree/dev/src/Abp.Zero/MultiTenancy)

thanks

**Comment by joeaudette** [comment]
the first tenant created is marked in the data with IsServerAdminSite = true. admins in that tenant can create and manage other tenants from the UI already. only way to promote another tenant to be able to do that is in the data not in the UI.

there is a config setting to hide the delete button by default to avoid accidental delete of tenants, but it can be enabled if you want to be able to delete tenants.

no plans for impersonation, to test just create a user account with roles and test it

currently supports sms for 2 factor, no current plans for anything else

user activity tracking and telemetry is not currently implemented but under consideration how best to implement it
