### ISSUE TITLE
SPA does not seem to work

### ISSUE THREAD

**Issue by nigel-dewar** [joeaudette/cloudscribe#126]
Hi Joe,

project loads up great, but SPA does not seem to work. when loading /app.html I get a bunch of errors. Also I cannot login using the SPA.

Is there something one must do to config this to work?

Cheers

**Comment by joeaudette** [comment]
those files in this repository are just remnants of something I was working on, they are not working samples.

cloudscribe core itself is an mvc app. There is integration available with IdentityServer4 and it can be used to protect apis consumed by spa apps but the sample for that is in the [cloudscribe StarterKits repo](https://github.com/joeaudette/cloudscribe.StarterKits) not in this one. I have a sample spa built with polymer/webcomponents [here](https://github.com/joeaudette/cloudscribe.StarterKits/tree/master/cloudscribe-idserver-nodb) , see the htmlclient project in that solution

**Comment by nigel-dewar** [comment]
thanks very much Joe.

I rekon a pattern that works well is to embed angular within asp.net mvc pages as required. So mini-spa pattern. Since lets face it, not all pages in an application require angular, really its usually when u needed some fancy client side action like an admin panel or so.

This way i dont have to worry about things when i use your cool routing system when you create another tenant.

Thanks so much for your hard work on this. It really is amazing what you have done. Im still trying to wrap my head around it all. Well done.


Sent from Samsung Mobile


-------- Original message --------
From: Joe Audette
Date:05/03/2017 07:47 (GMT+10:00)
To: joeaudette/cloudscribe
Cc: nigel-dewar , Author
Subject: Re: [joeaudette/cloudscribe] SPA does not seem to work (#126)


Closed #126<https://github.com/joeaudette/cloudscribe/issues/126>.
