### ISSUE TITLE
Error adding 'Same' scopes on different tenants

### ISSUE THREAD

**Issue by nigel-dewar** [joeaudette/cloudscribe#131]
Hi There Joe,

Using this source. https://github.com/joeaudette/cloudscribe 

getting this error: 
    An unhandled exception occurred while processing the request.

    SqlException: Cannot insert duplicate key row in object 'dbo.csids_IdentityResources' with unique     index 'IX_csids_IdentityResources_Name'. The duplicate key value is (openid).
The statement has been terminated. 

How to replicate:
1. Setup a client tenant1jsclient in base 'default' tenant.
2. Create another tenant and try to create a new client with same id tenant1jsclient. *** You will get this error ***

How to replicate
1. Setup ientity resource in base 'default' tenant for openid
2. Create another tenant and try to create an identity resource of openid.  *** You will get this error ***

Cheers

nige

**Comment by nigel-dewar** [comment]
For Now (unless advised otherwise) I have removed the index on the 'name' properties for 
'Client' and 'IdentityResource' in the 'ConfigurationDbContext.cs' under 'cloudscribe.Core.IdentityServer.EFCore.MSSQL'

I do not know what the consequences will be yet. There is likely a good reason which I do not know about yet as to why this property had an index. Although I do see in the queries in other places that usually a query for both 'siteId && (name)' are being used, so I hope it does not break things for me.

I understand that one would not want 2 clients using the same name hence in the same site, or things will break. For me however this would not be an issue.

What I am looking to achieve anyway is an easy setup for the embedded SPA within MVC page, so I wanted simplification, and not having to change clientid, idenityresources etc is my desired outcome here.

This said, if a SPA is embedded within MVC page then I could pass custom config in anyway like so

passing in tenant object;
var config = {
    authority: "http://localhost:5000/" + tenant.tenantfolder,
    client_id: tenant.name + "jsclient",
    redirect_uri: "http://localhost:5000/" + tenant.tenantfolder + "/callback.html",
    response_type: "id_token token",
    scope: "tenant.scopes",
    post_logout_redirect_uri : "http://localhost:5000/" + tenant.tenantfolder + "/index.html",
};

or something like that.

**Comment by joeaudette** [comment]
reopened this so I don't forget to look into it, sounds like a bug

**Comment by joeaudette** [comment]
this should be fixed now in both the source solution and in the starterkits
