### ISSUE TITLE
Potential Bug: error with roleadmin

### ISSUE THREAD

**Issue by nigel-dewar** [joeaudette/cloudscribe#133]
Using latest repo https://github.com/joeaudette/cloudscribe

Using Visual Studio 2017. Windows 7.

Error when visiting page: http://localhost:5000/roleadmin

    An unhandled exception occurred while processing the request.

    InvalidOperationException: No value provided for required parameter '_outer_Id'.
       Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.CreateCommand(IRelationalConnection connection, IReadOnlyDictionary<string, object> parameterValues)

The following may assist.

cloudscribe.Core.Storage.EFCore.Common.UserQueries+<GetRolesBySite>d__31.MoveNext() in UserQueries.cs
+
            return await listQuery
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
cloudscribe.Core.Identity.SiteRoleManager+<GetRolesBySite>d__12.MoveNext() in SiteRoleManager.cs
+
            return await queries.GetRolesBySite(siteId, searchInput, pageNumber, pageSize, CancellationToken);
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
cloudscribe.Core.Web.Controllers.RoleAdminController+<Index>d__13.MoveNext() in RoleAdminController.cs
+
            model.SiteRoles = await RoleManager.GetRolesBySite(

cheers

**Comment by joeaudette** [comment]
Hmm, that code was working before and has not changed recently. From searching about the error I found it is [apparently a bug/regression in EF Core 1.1.1](https://github.com/aspnet/EntityFramework/issues/7714)

It will be fixed in 1.1.2 but no release date on that yet. The issue describes a workaround using anonymous types that I can try, but I worry there may be other queries in other places with this same issue.

**Comment by nigel-dewar** [comment]
No worries Joe. Thats the hard part trying to code against fast changing stuff eh. Like trying to build a house on moving ground.

Is the other branch for rc2 still current? Or you fully focused on core 1.1 now?

Cheers.


Sent from Samsung Mobile


-------- Original message --------
From: Joe Audette
Date:21/03/2017 22:35 (GMT+10:00)
To: joeaudette/cloudscribe
Cc: nigel-dewar , Author
Subject: Re: [joeaudette/cloudscribe] Potential Bug: error with roleadmin (#133)


Hmm, that code was working before and has not changed recently. From searching about the error I found it is apparently a bug/regression in EF Core 1.1.1<https://github.com/aspnet/EntityFramework/issues/7714>

It will be fixed in 1.1.2 but no release date on that yet. The issue describes a workaround using anonymous types that I can try, but I worry there may be other queries in other places with this same issue.

**Comment by joeaudette** [comment]
I've got this fixed with the workaround in the source solution, the issue still exists in the starter kits but I should be able to fix it as soon as nuget.org gets around to indexing the new package I uploaded, for some reason it is taking a long time for the package to become available

**Comment by joeaudette** [comment]
this issue should be fixed now in starter kits

there was a stale branch from rc1 that I didn't know was still around, I've deleted that branch, everything is focused on 1.1 and vs2017

**Comment by nigel-dewar** [comment]
Awesome Joe. Thank you so much.


Sent from Samsung Mobile


-------- Original message --------
From: Joe Audette
Date:21/03/2017 23:54 (GMT+10:00)
To: joeaudette/cloudscribe
Cc: nigel-dewar , Author
Subject: Re: [joeaudette/cloudscribe] Potential Bug: error with roleadmin (#133)


I've got this fixed with the workaround in the source solution, the issue still exists in the starter kits but I should be able to fix it as soon as nuget.org gets around to indexing the new package I uploaded, for some reason it is taking a long time for the package to become available
