### ISSUE TITLE
We need to have more documentation and practical examples of how to use it

### ISSUE THREAD

**Issue by robertosistemas** [joeaudette/cloudscribe#159]
We need to have more documentation and practical examples of how to use it. See this project as it is well documented: https://www.aspnetboilerplate.com/Pages/Documents

**Comment by joeaudette** [comment]
same answer here as [your other post](https://github.com/joeaudette/cloudscribe.StarterKits/issues/28)

Yes I acknowledge more and better documentation is needed. This is not news to me. I am one person working on a bunch of open source projects unpaid. It is going to take time to get to documentation.  I'm doing the best I can.

Meanwhile you are free to ask specific questions here or in our [gitter chat](https://gitter.im/joeaudette/cloudscribe) and you and any others are free to help with documentation.

**Comment by joeaudette** [comment]
fyi documentation work is under way here https://www.cloudscribe.com/docs
