### ISSUE TITLE
Can not view in view browser

### ISSUE THREAD

**Issue by sengkok** [joeaudette/cloudscribe#16]
Hi joe , 
i follow your instruction to add the source to my VS . 
After rebuild , i try to Right click the example.WebApp project and choose View > View In Browser,
it open a page http://localhost:54671/ in browser , but with error "HTTP Error 502.3 - Bad Gateway
There was a connection error while trying to route the request."
What step i have miss from the setup ? i try to put   http://localhost:54671/Setup in the url , but same error appear.
I like your mojoportal design and use it for long time , and i do hope can continue use your new project in the future . 
Thanks

**Comment by joeaudette** [comment]
Hi,

It is working for me. 

I just updated [the wiki page](https://github.com/joeaudette/cloudscribe/wiki/Working-with-the-source-Code) to mention that now you need VS 2015 update 1 and you must also install ASP.NET 5 rc1 update 1

Please let me know if that does not solve it for you.

Hope that helps,

Joe

**Comment by sengkok** [comment]
Hi Joe, 
Yes , i have both updated version with IIS express 10 . 
I suspect maybe some configuration problem , cause i follow the example to create a asp.net 5 web application,it work but no luck on your source.
Let me try to figure out , or maybe i can downgrade to iis8 ? 
Thanks 

SK

**Comment by Tovli** [comment]
That usually means that you have referenced a dll that isn't compatible with the new .net version. 
Or you created a new project before updating to update 1. The configurations has changed
