### ISSUE TITLE
Change DateTime to DateTimeOffset

### ISSUE THREAD

**Issue by Tovli** [joeaudette/cloudscribe#17]
Hi,
I would like to offer to change the DateTime properties to DateTimeOffset. That way we will be able to use the cloud more freely with out always worrying about transferring to/from Utc.
This type has native support by SQL and By the Many NoSQL c# drivers

**Comment by joeaudette** [comment]
maybe you could elaborate more on the code changes that would be needed and the resulting benefit. Much of my data model came from mojoPortal and I also have to factor in my desire to keep a possible easy migration from mojoPortal to cloudscribe. So changes  in the data model must be thought  through carefully to ensure a smooth upgrade. I'm used to working with dates stored as utc and it does not seem unreasonable way to store them.

**Comment by coe-jeubanks** [comment]
Hi, Joe. From some quick research it seems that [DateTimeOffset is the newer, preferred way of storing datetime values](http://blogs.msdn.com/b/davidrickard/archive/2012/04/07/system-datetime-good-practices-and-common-pitfalls.aspx). However, it looks like there are [issues with supporting DateTimeOffset in the MySQL .NET connector](http://bugs.mysql.com/search.php?cmd=display&status=Active&tags=DateTimeOffset). I haven't checked to see how well the other mojoPortal database types are handling it.

Jamie

**Comment by joeaudette** [comment]
Hey Jamie,

That is an interesting article but it doesn't really show much nuts and bolts about working with DateTimeOffset vs using UTC dates.
Specifically more info is needed about how that is used when we need to adjust to specific time zones, ie if the user has a time zone specified we want to use adjust times to that timezone for display and if the user is not authenticated or doesn't have a time zone specified then we want to have a timezone that is the default for a site. We still need to use client side javascript date pickers and time pickers and we need to convert back and forth from the correct time zone right? 

Maybe there are clear ways of doing those things but they are not shown in the article. 

I would also be concerned about whether it would limit us for use of sqlite, sqlce etc. ie does use of DateTimeOffset require a db that supports that data type?

There are a lot of issues with working with DateTime that I am currently comfortable with and know how to deal with, so while there may be some possible benefit to changing to a new way, it doesn't really scratch anything that is itching all that much from my point of view.

The latest [dotnet rocks show that came through my rss feed also talks about datetime](http://www.dotnetrocks.com/default.aspx?ShowNum=1230) and I have added it to my listening cue for later today.

maybe we should also consider using [noda time](http://nodatime.org/)

at the moment there are many other things in this project that need attention sooner than this from my point of view. At the moment datetime handling is something that I already have a working solution for, maybe there are better solutions but I don't want to be sidetracked from other things right now.

**Comment by coe-jeubanks** [comment]
I agree, Joe. Unless there's a stronger use case than developer convenience for localized-only use of cloudscribe, it doesn't seem high priority to me. I did find this [other article about DateTime versus DateTimeOffset](https://msdn.microsoft.com/en-us/library/bb384267%28v=vs.110%29.aspx) that has some examples of actual usage.

**Comment by joeaudette** [comment]
It is definitely something that I think deserves more thought. Once I feel more caught up on other project goals I do intend to revisit this, do more research and make a decision, so I will leave this issue open.

**Comment by coe-jeubanks** [comment]
FWIW, I think Noda Time does look really good. That might be the ticket to get improved convenience, functionality, and bug-proofing of Date/Time storage and use. [This blog post](http://blog.nodatime.org/2011/08/what-wrong-with-datetime-anyway.html) really covers all of the issues.

**Comment by joeaudette** [comment]
using NodaTime, storing dates as utc
