### ISSUE TITLE
Themes file not getting copied on publish

### ISSUE THREAD

**Issue by nbangera** [joeaudette/cloudscribe#178]
Publishing website from visual studio 2017 does not copy theme file.

on publishing the site I am expecting SharedThemes\{theme}\ to contain wwwroot contents (js\cs\...)
But files are not getting copied. refer to attached snapshots.

![image](https://user-images.githubusercontent.com/23654369/27251344-848df31a-5362-11e7-877a-9512c9e3713f.png)

![image](https://user-images.githubusercontent.com/23654369/27251364-1759c02a-5363-11e7-983d-5d2b7e12334c.png)

**Comment by joeaudette** [comment]
are you using the StarterKit samples? I am pretty sure I encountered this issue and solved in the .csproj files for the StarterKits as in [this example](https://github.com/joeaudette/cloudscribe.StarterKits/blob/master/cloudscribe-core-ef-mysql/src/WebApp/WebApp.csproj)

    <Content Include="**\sitefiles\**\wwwroot\**" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="SharedThemes\**\wwwroot\**" CopyToPublishDirectory="PreserveNewest" />

**Comment by nbangera** [comment]
Thank you very much solution you provided did fix the issue.
