### ISSUE TITLE
Sharing JS files

### ISSUE THREAD

**Issue by lchilson** [joeaudette/cloudscribe#179]
Can on js file be shared with all the themes or does it need to be copied in every location?

also is there a chance on getting a bit more description on what the multitenant options mean in the appsettings

**Comment by joeaudette** [comment]
the combination of taghelpers triggered by special attributes and static file middleware allows static files to be served from theme specific wwwroot folder, which is nice for making themes portable and self contained, but you don't have to do that, you can have some resources from the theme wwwroot folder and some from the main wwwroot folder.

you could put common js and css in the main wwwroot folder. To use resources from within the theme wwwroot folder requires special attributes for the taghelper, if you leave those attributes out then the urls like ~/somefile.js would resolve to the main wwwroot folder. 

https://www.cloudscribe.com/docs/themes-and-web-design

**Comment by lchilson** [comment]
ah ok thanks
