### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by Tovli** [joeaudette/cloudscribe#18]
Hi,
Why are you using a DIY logging rather then the popular frameworks? (i.e. log4net, serilog etc.)

**Comment by joeaudette** [comment]
I implemented logging to the database. I'm not imposing on anyone to use my logger I only provide it as an alternative. When I started working on cloudscribe serilog was not ready and there was not a compatible nuget. As far as I know it is not yet possible to use log4net on dnxcore50. The bottom line is my logger does not need those loggers and it works now but people are free to use whatever loggers they want in the startup configuration of their own app.
