### ISSUE TITLE
Site Events Question

### ISSUE THREAD

**Issue by Roycode** [joeaudette/cloudscribe#183]
how to use site events? how to create a Site Created handler plugin. Is there an example?

**Comment by joeaudette** [comment]
I haven't got to documenting that stuff yet, but it is pretty straightforward.
Basically just implement any of those [event handler interfaces](https://github.com/joeaudette/cloudscribe/tree/master/src/cloudscribe.Core.Models/EventHandlers) that interest you, and inject them as scoped. Then your handler will be invoked when the event happens.

**Comment by Roycode** [comment]
Got it. Thanks Joe.

**Comment by Roycode** [comment]
Hi Joe. another question, do you know if MS give us a way to trigger startup?

**Comment by joeaudette** [comment]
From a quick google I found this:
https://stackoverflow.com/questions/36121999/how-to-restart-asp-net-core-app-programmatically
but that answer shows only ow to stop an app not restart it.

There is also some possibility to use dotnet watch to restart an app if a file changes
https://github.com/aspnet/DotNetTools/blob/dev/src/Microsoft.DotNet.Watcher.Tools/README.md
That is what is used for restarting in development environments and I guess it could be used in production if you really need it.

With IIS hosting as a proxy in front of kestrel, I think the easiest way would be to write code to "touch" the web.config file which would trigger IIS restart
