### ISSUE TITLE
Password validation message(s) not displaying on user registration form

### ISSUE THREAD

**Issue by hefin1** [joeaudette/cloudscribe#194]
Using the cloudscribe starter kit project [SimpleContent-cloudscribecore-ef](https://github.com/joeaudette/cloudscribe.StarterKits/tree/master/SimpleContent-cloudscribecore-ef) navigating to the user registration form `account/register` entering a password that doesn’t meet the password requirements, the form submits but bounces the user site root - No user account is created.

Logging in as an admin in the system logs you can see a warning for `password validation failed`

![image](https://user-images.githubusercontent.com/13196509/27839329-53de64b4-60e8-11e7-9823-f938a3812997.png)

Expected behaviour would be the same as on the  `/useradmin/newuser` form which displays password validation message if the password does not meet requirements on submission

![image](https://user-images.githubusercontent.com/13196509/27839337-62339bd8-60e8-11e7-8b57-6c9ecb42f780.png)

**Comment by joeaudette** [comment]
Thanks for the bug report! This is now fixed in the latest nugets.
