### ISSUE TITLE
People can use IdentityServer without cloudscribe.Identity

### ISSUE THREAD

**Issue by mikeandersun** [joeaudette/cloudscribe#21]
IdentityServer has a `IUserService`  interface that can be implement to communicate with an accounts management database. I did some work to implement that with  `clouldscribe.Identity`. But the work was hard to me because they don't support ASP.NET 5 and have their DI system. 
BTW, I think the best point to start is:

1) Setup a cloudscribe-based web application client to accounts management and user registration.
2) Implement `IUserService` with `clouldscribe.Identity` to connect to the accounts management client database.
3)Hosting IdentitySever in a cloudscribe-based web app is good idea to get some hosting features but it need to have 2 first.
Accounts management as a client for IdentityServer is a nice a simple approach and Dominick Baier recommened it. I think google have the same architecture(`account.google.com` as Identity server and `myaccount.google.com` for user that can manage his/her account.
But for now I need to interact from my cloudscribe-based web app with my hosted IdentityServer.This is my reason that I don't need to having  `clouldscribe.Identity` in my cloudscribe-based web app at all.
Thanks for attention.

**Comment by alexsandro-xpt** [comment]
+1

**Comment by joeaudette** [comment]
I have completed my initial work on IdentityServer4 integration and have created samples in our [StarterKits repo](https://github.com/joeaudette/cloudscribe.StarterKits)

Note that I decided number 2 above is not a goal for this project. Specifically I'm saying it is not a goal for cloudscribe Core to be a client for IdentityServer. cloudscribe Core with IdentityServer4 integration is only intended to provide a back end and management of tenants, users, roles, claims, clients and scopes. 

My integration provides a complete ready to use solution to stand up an OP Server (OpenId Connect Provider) with all the needed management UI already built for you. You can use it as a single tenant OP Server but it also can be used as a multi-tenant OP Server. Using tenants based on the first folder segment of the url makes it easy to provision new OP Servers in the same installation, each with their own users, roles, claims, clients, and scopes. It also supports host name based tenancy but the advantage of the folder based approach is that you can provision new tenants without needing any new DNS records and without needing a separate SSL certificate for each one.

There is one sample using Entity Framework Core and a ready to run OP Server, and another sample uses NoDb, so I could pre-populate the sample with 2 tenants and working clients and api scopes for each tenant. The NoDb sample is the best one to try it out and see how it works, while the Entity Framework sample is probably what you want if you decide to use for your own projects.
