### ISSUE TITLE
breaking changes coming in asp.net core 2.0

### ISSUE THREAD

**Issue by joeaudette** [joeaudette/cloudscribe#215]
This issue for notes about breaking changes in asp.net core 2.0 and how those changes will impact cloudscribe Core. There are breaking changes that will require changes in cloudscribe Core before we can support asp.net core 2.0

### netcore20 branch status
most things are working as they should, still working on multi-tenant social auth, google and microsoft are working

## Issues to Tackle

Breaking changes are listed in the [announcements repo](https://github.com/aspnet/Announcements), and there may be other breaking changes that will also impact this project, in addition to the ones listed below.

### Breaking Changes in Auth and Identity

The biggest problem identified so far is that we will no longer be able to pass cookieauth options directly to the middleware when branching per tenant. The calls to app.UseCookieAuthentication are not implemented and throw exceptions in the 2.0 stack.
The announcement for these breaking changes is here:
https://github.com/aspnet/Announcements/issues/262

In the 2.0 stack we can only provide the settings via DI. From a cursory review of the [latest asp.net code](https://github.com/aspnet/Security/tree/dev/src/Microsoft.AspNetCore.Authentication.Cookies), it looks like a possible solution will be to implement a custom [PostConfigureCookieAuthenticationOptions](https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.Cookies/PostConfigureCookieAuthenticationOptions.cs). I'm not sure yet if that is the best solution, it would be nicer if that had virtual methods so we could override and call the base method, then customize the options for the current tenant/site.

Needs further research to better understand the new auth system and available extension points. The main source repos to study are [Security](https://github.com/aspnet/Security) and [HttpAbstractions](https://github.com/aspnet/HttpAbstractions)

From a quick review of the [Identity repo](https://github.com/aspnet/Identity) I think the breaking changes in Auth also bring breaking changes in Identity. Particularly SignInManager now uses constants for the authschemes so we will need to override more of the virtual methods to use per tenant auth schemes. It also has changed constructor dependencies so our derived class SiteSignInManager will have to be updated

There are [breaking changes in how cookies are configured](https://github.com/aspnet/Announcements/issues/257)

There are breaking changes in [logging configuration](https://github.com/aspnet/Announcements/issues/255) that probably also impact us at leastin the StarterKits

There is a [breaking change in localization](https://github.com/aspnet/Announcements/issues/260) that probably impacts cloudscribe.Web.Localization

**Comment by joeaudette** [comment]
Multi-tenant auth and auth in general are broken at the moment in the netcore20 branch

Got some good advice on these issues on this thread https://github.com/aspnet/Security/issues/1338

**Comment by joeaudette** [comment]
multitenant cookie auth is working now, as are microsoft and google social auth, hope to finish the rest of the social auth tomorrow

**Comment by joeaudette** [comment]
new breaking changes related to authentication in 2.0 rtm

**Comment by RutNai** [comment]
Is google auth break ATM?

I got "InvalidOperationException: sub claim is missing" when doing google auth.

cloudscribe.Core.IdentityServerIntegration.Mvc : 2.0.0-preview20170822

**Comment by joeaudette** [comment]
@RutNai thanks for the bug report, I am able to reproduce this problem. I will investigate this today.

**Comment by joeaudette** [comment]
@RutNai so far I have determined it is the identityserver integration that is breaking social auth, when I comment that out it works as expected. Will continue to investigate a solution.

**Comment by joeaudette** [comment]
@RutNai this should be fixed now if you do dotnet restore --no-cache to get the latest nugets

Thanks again!

**Comment by RutNai** [comment]
#228
@joeaudette Fixes confirmed. 

Thank you too!
