### ISSUE TITLE
Permit configuration of password policy

### ISSUE THREAD

**Issue by CrispinF** [joeaudette/cloudscribe#219]
We were expecting to be able to set password policy in startup.cs something like
services.Configure<IdentityOptions>(options =>
            {
                options.Password.RequireDigit = false;
                options.Password.RequiredLength = 7;
                options.Password.RequireLowercase = true;
                options.Password.RequireNonAlphanumeric = false;
                options.Password.RequireUppercase = true;
            });
but it turned out this is set within cloudscribe and only the minimum length can be easily altered at present (in database).
@joeaudette my colleague Hefin asked about this, and you confirmed we could fork the class and inject a forked version. 
Our projects/clients will expect to be able to alter password policies "easily" (without code modifications), probably through the administrative interface. e.g. under Administration > Security Settings. We may also need to support different settings per tenant (which would suggest holding all the settings in the db).
Could we just check then - is this on your roadmap anyway? Or is it something we could contribute to the project?

**Comment by joeaudette** [comment]
@CrispinF I would consider putting those settings in the database so it would be possible to change them directly in the database. I am not keen on surfacing that stuff in the UI and inviting people to change that stuff. Would you be satisfied with that?

Personally, if I had a customer asking me for weaker password settings I would feel it my responsibility to push back on that for their own good. Those defaults were well chosen by the Microsoft security team. I could see the case for being able to make the requirements stronger for sites with high security needs, but I really cannot think of any situation where I would ever not push back if someone wants to weaken those settings.

**Comment by CrispinF** [comment]
@joeaudette yes, in DB, per tenant, would be fine. I agree dangerous to surface these to site admins.
The reason is we often work with large gov & organisations that set their own password policies and then insist that all systems comply. These are often stronger than the MS defaults (but not always!). 
The other thing they ask for is expiry periods and password retention to ensure resets do not re-use earlier ones - I think we logged an issue about that a long time ago #1 ;-)

**Comment by joeaudette** [comment]
@CrispinF this timely article by Troy Hunt came out yesterday https://www.troyhunt.com/passwords-evolved-authentication-guidance-for-the-modern-era/

The current recommendation is Do Not Mandate Regular Password Changes.
My goal is to follow OWASP guidelines and Troy Hunt is the most well known OWASP expert on the planet. 

I am not inclined to implement expiry periods within cloudscribe core. It could be implemented and enforced externally by custom code if someone really needs that. Nothing is blocking that. If you or someone else really needs that enough to pay for it I would be willing to implement it under sponsorship as open source in a separate package that would be easy to integrate.

**Comment by joeaudette** [comment]
@CrispinF on moving those settings to the db, do you need that urgently? It would be easier for me to focus on that for cloudscribe Core 2.0 which will correspond to asp.net core 2.0 which will be released soon in Q3 this year and I expect cloudscribe 2.0 to ship immediately after that. Actually working on preview version now.

**Comment by CrispinF** [comment]
@joeaudette no argument with Troy!  Again this is about fulfilling contractual requirements with clients who are not always so wise.
Password settings in DB is not urgent, so bringing this with cloudscribe Core 2.0 would be fine.

**Comment by joeaudette** [comment]
@CrispinF if you want me to sponsor me to build something to manage password expiry and settings for that per tenant we can discuss is privately.

For now I can tell you a relatively easy solution you could use to meet the contractual requirements.

1. Since we already do keep track of the last password change date on siteuser, you could easily implement a middleware that checks the last password change date and if expired forcibly redirect the user to the change password page.
2. You would probably want to customize the view to detect the expired password and explain to the user why they are forced to that page

**Comment by joeaudette** [comment]
Another quick and dirty way to implement a password policy would be with a daily scheduled stored procedure that would update the MustChangePwd field on the user if the password is older than permitted.
 
The site rules middleware that we have already will forcefully redirect the user to the change password page if that property is true. It was implemented to support adding users from the administration section and forcing the user to change the temporary password that the administrator used when creating the account.

**Comment by CrispinF** [comment]
@joeaudette thanks those are useful tips to bear in mind when we are box-ticking!

**Comment by joeaudette** [comment]
these properties are now in the database in cs_Site table in the 2.0 preview version, so closing this issue

**Comment by joeaudette** [comment]
Interesting news that now the recommendation for requiring special characters in passwords is no longer recommended. It is more important that passwords are long.

http://gizmodo.com/the-guy-who-invented-those-annoying-password-rules-now-1797643987
