### ISSUE TITLE
Search on /roleadmin/rolemembers not working (and so cannot add user to role)

### ISSUE THREAD

**Issue by CrispinF** [joeaudette/cloudscribe#220]
The Search button jumps you back to /roleadmin/index
See in new site from starter kit and also in https://colchesterheritage.co.uk 
I think this means we cannot add a user to a role (?), so I've had to do this in the database on my new site.

**Comment by joeaudette** [comment]
@CrispinF this should be fixed now if you get the latest packages with dotnet restore --no-cache

It was a bug in the view not passing the siteid and roleid correctly

It did not prevent adding users to roles though, it just prevented searching on existing role members, the add button still opened a modal with a list of users not in the role which also has working search

**Comment by CrispinF** [comment]
@joeaudette thanks. And I'm so impressed that running a one line command has this fixed at my end immediately. Didn't even have to close VS or the site in browser!

**Comment by joeaudette** [comment]
@CrispinF not like the mojoportal days when you would have to wait for a new release of a big monolithic app and upgrade the whole thing to get a bug fix, definitely more agile now

thanks for the bug report! closing this issue
