### ISSUE TITLE
Role Name changes not coming into effect against user 

### ISSUE THREAD

**Issue by hefin1** [joeaudette/cloudscribe#223]
Hey Joe I think this is a bug, I'm finding a role name change in CS are not coming into effect against user when `IsInRole()` is called 

Steps to Illustrate/Reproduce 
============

- Say UserA is in role `Form View` we can run `User.IsInRole("Form View")` which will be true

- When a role name is renamed for example from `Form View` to `Form Viewer`  in the Role Admin section, we can re-run the code `User.IsInRole("Form View")` is still `TRUE` and `User.IsInRole("Form Viewer")` is `FALSE`.

- I found the user had to be removed and added back the newly renamed role of `Form Viewer`.  User.IsInRole("Form View") is then `FALSE` and User.IsInRole("Form Viewer") is now `TRUE`

I'm was expecting the a role name change would update/change/re-assign all users in the role to the new role name.

**Comment by joeaudette** [comment]
If I recall correctly this is by design, roles have a name for display and a normalizedname and normalized name is not intended to ever change and is the actual role name. So for example someone can rename the administrators role for localization without breaking it because it only changes the name that is displayed.
If your intention is to really rename the role and the underlying normalized name, you should delete the role and then create a new one with the desired name.

**Comment by joeaudette** [comment]
renaming a role will not update any user's roles and the user role cookie will not be updated automatically.
However if the role membership of the user changes ie added or removed from a role then the cookie will get updated automatically

**Comment by hefin1** [comment]
Sure makes sense, thanks joe

**Comment by joeaudette** [comment]
actually does look like role names can be changed and it does break existing roles if that happens. I was thinking of how it worked in mojoportal with display name. So renaming the admin role can break administrative access

**Comment by CrispinF** [comment]
Returning to the OP, would it be possible to force updating the role cookie when the role name is changed? That would fix Hefin's problem.

**Comment by joeaudette** [comment]
renaming roles is not a frequent task so I don't think we need anything built in for this.

However, what you could do is run a sql statement to set the cs_Users.RolesChanged flag to true for all rows then all users will get there cookies updated whether they were impacted by the role name change or not. That is the flag we set if the role membership of the user is changed and we have existing built in middleware that will detect that flag and sign the user out and in again which gets them a new cookie

**Comment by joeaudette** [comment]
or you could use a query based on the specific roleid but more simple just to update all rows
