### ISSUE TITLE
OpenIdConnect Authentication Error

### ISSUE THREAD

**Issue by ticky74** [joeaudette/cloudscribe#224]
When using the OpenIdConnect authentication provider in the starter kit for id-server I'm getting this error. I am trying to specifically authenticate with the Azure 2.0 endpoint. 
I am pretty sure the setup on that end is okay, I can authorize with a test angular app, however I'm not sure where exactly the crossed wires are. I know @joeaudette mentioned a fork of identity server, I'm not sure if that is related or not. If someone can point me in the right direction that would be great.
Thanks for this project.

An unhandled exception occurred while processing the request.

OpenIdConnectProtocolException: IDX10336: Both 'id_token' and 'access_token' should be present in OpenIdConnectProtocolValidationContext.ProtocolMessage received from Token Endpoint. Cannot process the message.
Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolValidator.ValidateTokenResponse(OpenIdConnectProtocolValidationContext validationContext)

AggregateException: Unhandled remote failure. (IDX10336: Both 'id_token' and 'access_token' should be present in OpenIdConnectProtocolValidationContext.ProtocolMessage received from Token Endpoint. Cannot process the message.)
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler+<HandleRemoteCallbackAsync>d__6.MoveNext()

**Comment by joeaudette** [comment]
The openidconnect settings under Administration > Social Auth Settings have nothing to do with identityserver integration.  

IdentityServer is an openideconnect provider so those settings can be used to connect to authenticate against a remote installation of identtityserver but not the locally integrated identityserver. 

There are 3 menu items related to identityserver integration for clients, apis and identity resources. Using those menu areas you can setup connections from remote apps and apis to authenticate using the users and roles managed in cloudscribe core.

Without a lot more details about what you are doing and how you have things configured I cannot help you. I do not even consider myself an expert in using identityserver so their documentation and gitter chat and stackoverflow are much better resources for questions about using it and configuring it.

There are examples of working clients and apis in  the nodb version https://github.com/joeaudette/cloudscribe.StarterKits/tree/master/cloudscribe-idserver-nodb
so maybe the configuration seen there could be helpful to you.

**Comment by ticky74** [comment]
Thanks @joeaudette, actually your explanation of the relationship was very helpful and problem is solved. Nothing to do with any software issues so I'm gonna close this. I will do up the quick tutorial I promised to wire up cloudscribe to your Azure AD over the weekend. Thanks again. ian
