### ISSUE TITLE
Asp.net Identiy auth cookie by tenant

### ISSUE THREAD

**Issue by learntecno** [joeaudette/cloudscribe#248]
@joeaudette , by default the auth cookie isolation is by domain, how did you manages that by Query string(Tenant), please guide me. Thanks.

**Comment by joeaudette** [comment]
I didn't do it by query string but you could, I did it by the first folder segment of the url and then only conditionally if we are using that for tenant resolution as cloudscribe supports both host name or folder based tenants but it is mutually exclusive, ie you can use one or the other approach by configuration but not both.

The main thing I did to control cookieoptions per tenant was to implement and inject a custom:

    IOptionsMonitor<CookieAuthenticationOptions>

as [SiteCookieAuthenticationOptions](https://github.com/joeaudette/cloudscribe/blob/master/src/cloudscribe.Core.Identity/SiteCookieAuthenticationOptions.cs), and I used a similar approach also for each of the social auth options

There are a couple of other things I did as well. I have a custom UserClaimsPrincipalFactory where I add an extra claim with the tenant id, and a custom cookie validator where I reject the principal if it doesn't have the right tenant id claim.

**Comment by joeaudette** [comment]
if you are using identityserver with a remote web api then the remote web api  must use jwt not cookies right? 

I don't know the answer off the top of my head on how to do that but you can include a claim with the tenant id in the jwt token and maybe use that to resolve the tenant in the api
