### ISSUE TITLE
feedback requested - IdentityServer integration

### ISSUE THREAD

**Issue by joeaudette** [joeaudette/cloudscribe#257]
Recently Kevin Vickers asked on twitter whether there has been any progress getting needed changes in IdentityServer so that we don't need a fork.

The answer is no, and I am not feeling optimistic that it is going to happen any time soon.

The thing to understand is that the changes needed are only to support the folder based multi-tenancy in cloudscribe Core. To do that we need IdentityServer endpoints to allow the extra folder segment in the url.
I do think we could support the host name based multi-tenancy without forking IdentityServer.

So my questions to the community are

1. how many are using our IdentityServer integration at all
2. how many are using it with multi-tenancy vs just a single tenant
3. how many really need the folder based mutli-tenancy to work with IdentityServer

Folder based multi-tenancy has the advantage of being very easy to provision new tenants as opposed to host name based multi-tenancy which requires additional DNS settings and web server settings to make new tenants work.

So the trade-off to consider is whether we could drop support for using folder tenancy with our IdentityServer integration. If we do that I think we could change to just use the standard IdentityServer instead of our custom fork. We cannot do both though, if we really need the folder based multi-tenancy to work with IdentityServer we will have to continue using a fork.

I suspect that people may be a little uncomfortable about using a fork and would rather use the standard IdentityServer.

Anyone who has an opinion please weigh in and let me know about the 3 questions above and whether you think we should drop support of folder tenancy in order to not use a fork of IdentityServer.

Do note that I am not talking about removing support for folder tenancy in cloudscribe Core, I am not planning to do that, I am only talking about whether that scenario would be supported with Identityserver integration, so if not using IdentityServer integration this question does not apply to you.

**Comment by kmvickers** [comment]
hey joe

my answers .. 

i will be using the IS integration 

Multi tenancy is a plus for me 

if it gets me on a non forked IS then i can live with URL based as opposed to folder 


Best 
Kevin

**Comment by joeaudette** [comment]
Thanks @kmvickers ! I am inclined to agree but will wait a bit to see if I get more feedback

**Comment by tonydrake** [comment]
Well - I've just downloaded and built the solution for the first time last night - I'm trying to work out which version of multi-tenancy is best for me and playing with the basic setup. So far so good.

I DO want multi-tenancy, but not sure which way is best at present. I plan to create a second instance using URL over the weekend to test.

**Comment by mikeandersun** [comment]
I don't need folder-based tenancy at all, host-based is enough.
I think folder-based  is a extra bother on the solution. I did tried to make it as a plug in feature but could not get a result.
Thanks for your robust solution.

**Comment by joeaudette** [comment]
good news on this! I saw the [release announcement for identityserver4 2.0](https://leastprivilege.com/2017/10/06/identityserver4-v2/) a few days ago and the linked [changelog](https://github.com/IdentityServer/IdentityServer4/releases/tag/2.0.0) which pointed to some issues that made it sounds like it should now be possible to get it working with custom endpoint routes which is what I needed for the folder tenants.

I worked on it all day yesterday and this morning and got it working! Still need to do a little testing and then I can package new nugets and then I can update our project templates to use the new integration nugets and the official nuget for IdentityServer4

So we will be able to support folder multi-tenancy without needing a forked version of IdentityServer4

**Comment by joeaudette** [comment]
I have published updated nugets for identityserver4 integration, we no longer need a fork and it still supports folder tenants just as before.

Since there were breaking changes, I made the version 2.1 so that people using 2.0.0-* will not automatically get upgraded. There are changes in Startup.cs needed if you choose to upgrade.
Specifically, 

    services.AddIdentity()...

must be changed like this:

    services.AddIdentityServerConfiguredForCloudscribe()
                    .AddCloudscribeCoreNoDbIdentityServerStorage() // your storage choice here
                    .AddCloudscribeIdentityServerIntegrationMvc()
                    // https://identityserver4.readthedocs.io/en/dev/topics/crypto.html
                    //.AddSigningCredential(cert) // create a certificate for use in production
                    .AddDeveloperSigningCredential() // don't use this for production
                    ;

I have also updated the project templates for visual studio 2017 and for the dotnet cli so it will create new projects with the updated packages.

I have also updated the relevant StarterKit samples.

I am closing this issue.
Thanks all for your feedback.

**Comment by joeaudette** [comment]
Oops, I made a mistake when uploading nugets yesterday. I meant for all the idserver integration nugets to be version 2.1 but accidentally uploaded the data layer for MSSQL as 2.0 so the package failed to restore when creating a project that included identity server and mssql. I have fixed this by uploading a new package as 2.1. So if you encountered this issue you can solve it with dotnet restore --no-cache
