### ISSUE TITLE
SystemInfoManager should have the option to include other information as well

### ISSUE THREAD

**Issue by steven-r** [joeaudette/cloudscribe#279]
Currently SystemInfoManager has the option to include more information based on interface IVersionHandler. I would like to add other information as well (like build information, ...).

Does it make sense to have a similar interface like IVersionInfo that is not related to "Version" fields?

**Comment by joeaudette** [comment]
seems like you could override the view and add a partial view with any custom info you want, and inject your own services into the partial view as needed.
Don't think we need to bake something new in for this.

**Comment by steven-r** [comment]
hmmm... I was trying to prevent overwriting the views ... anyhow the approach seems feasable. I'll go with it.

**Comment by joeaudette** [comment]
nothing wrong with downloading specific views you want to customize to your local project, local views will override the embedded views. I customize views in my client projects on a regular basis.

**Comment by joeaudette** [comment]
I could potentially add an empty partial view into the main view for that, then you would only need to override the empty partial view to get your extra stuff in there.

**Comment by steven-r** [comment]
also a nice idea. I will continue with customizing the current version. If there's another option available later on, I will check this one out.

**Comment by joeaudette** [comment]
I can easily add an empty partial below the current content in the view, if that is sufficient for your needs. But that would not help if you want to add data into the same html table. As long as you don't need to do that then it would definitely be cleaner to only override the empty partial. Let me know, if that would work for you I'll do it in the next nuget publish and post here when that happens.

**Comment by steven-r** [comment]
As this information is for admins only, I could live with the extra partial. Thanks for the support ;)

**Comment by joeaudette** [comment]
I've added it and published new nugets so if you get the latest of all the cloudscribe nugets then you should be able to override just this empty partial to add your stuff
https://github.com/joeaudette/cloudscribe/blob/master/src/cloudscribe.Core.Web.Views.Bootstrap3/Views/SystemInfo/CustomContentPartial.cshtml
