### ISSUE TITLE
still use gitter?

### ISSUE THREAD

**Issue by back5576** [joeaudette/cloudscribe#28]
I searched for cloudscribe and got no hits

**Comment by joeaudette** [comment]
the link is a the bottom of the main readme

[![Join the chat at https://gitter.im/joeaudette/cloudscribe](https://badges.gitter.im/joeaudette/cloudscribe.svg)](https://gitter.im/joeaudette/cloudscribe?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
