### ISSUE TITLE
VS template gitignore

### ISSUE THREAD

**Issue by CrispinF** [joeaudette/cloudscribe#284]
The gitignore in the VS template doesn't exclude things like appsettings.Development.json
Is it possible to include a suitable file, or perhaps some guidance in the readme.html?

**Comment by joeaudette** [comment]
I'm not aware of including a .gitignore in the template at all, don't think I am, but worth pondering.

I could possibly add a gitignore in the WebApp folder with nothing but that one line to supplement the main gitgnore, and I could mention that the file is there  and why in the readme.

**Comment by CrispinF** [comment]
Perhaps the one we get is simply the default when we allow VS to create a Git repo. Your suggestion sounds good.

**Comment by joeaudette** [comment]
Actually after more thought, I cannot add a .gitgnore file for that in the template because if I do then that file will be gitignored in the [template repo](https://github.com/joeaudette/cloudscribe.templates). Best I can do is add a note in the readme recommending add it to your gitignore file

**Comment by CrispinF** [comment]
ok - good point!

**Comment by joeaudette** [comment]
I've added notes recommending to gitignore the appsettings.Development.json file in the latest template readme, so closing this
