### ISSUE TITLE
Auth0 support?

### ISSUE THREAD

**Issue by back5576** [joeaudette/cloudscribe#29]
I just found this project and find it quite interesting. All I've yet done is read the docs. 

I've done some dev experiments with Auth0 and I really like their paradigm - I like getting out of the identity business. But I have to add in my own multitenancy layer and that's where I fould cloudscribe. Am curious if you'd consider doing an Auth0 integration.

**Comment by joeaudette** [comment]
had not heard of [auth0](https://auth0.com/) until you posted it. I have no immediate plans to work with it. Doesn't accomplish anything I can't figure out how to accomplish without a 3rd party service so it doesn't look like it scratches anything that is itching for me. maybe will revisit it later

I'm more interested in working [identityserver4](https://github.com/IdentityServer/IdentityServer4) or  [openiddict](https://github.com/openiddict/openiddict-core)
