### ISSUE TITLE
Is there OpenIdConnect support?

### ISSUE THREAD

**Issue by mikeandersun** [joeaudette/cloudscribe#3]
I want to use this project as a client with [IdentityServer v3](https://github.com/IdentityServer/IdentityServer3)

**Comment by joeaudette** [comment]
I've been very interested in IdentityServer as well, and I am definitely interested in making it possible to use that in cloudscribe tenants.
At this point however, I think we have to wait a while for them to produce Nuget packages that are compatible with dnxcore50 before we can start trying to use it. I suspect that after asp.net 5 comes out of beta the 3rd party components will ramp up quickly in terms of what is available, but for now dnxcore50 is a very new thing. I'm sure they are working on it for IdentityServer and I will be keeping an eye out for their updates.

**Comment by mikeandersun** [comment]
I am waiting for good news

**Comment by joeaudette** [comment]
I was going to leave this issue open, feel free to re-open it. I marked it as enhancement because I think it is a good enhancement suggestion and I left it open because I'd like to implement this enhancement in the future.

**Comment by joeaudette** [comment]
I have completed my initial work on IdentityServer4 integration and have created samples in our [StarterKits repo](https://github.com/joeaudette/cloudscribe.StarterKits)

My integration provides a complete ready to use solution to stand up an OP Server (OpenId Connect Provider) with all the needed management UI already built for you. You can use it as a single tenant OP Server but it also can be used as a multi-tenant OP Server. Using tenants based on the first folder segment of the url makes it easy to provision new OP Servers in the same installation, each with their own users, roles, claims, clients, and scopes. It also supports host name based tenancy but the advantage of the folder based approach is that you can provision new tenants without needing any new DNS records and without needing a separate SSL certificate for each one.

There is one sample using Entity Framework Core and a ready to run OP Server, and another sample uses NoDb, so I could pre-populate the sample with 2 tenants and working clients and api scopes for each tenant. The NoDb sample is the best one to try it out and see how it works, while the Entity Framework sample is probably what you want if you decide to use for your own projects.
