### ISSUE TITLE
Get Tenant from user claims.

### ISSUE THREAD

**Issue by mikeandersun** [joeaudette/cloudscribe#30]
I have an API that call from an angular App. In the API I need tenantId to filter data from database.
What is the best solution for this? I think one of the following options.
1- Send tenantId from angular app to the API.
2-Get it from user claims.

**Comment by joeaudette** [comment]
users do have a claim named SiteGuid which contains the SiteGuid, so you can get it from there

for server side code you can also take a constructor dependency on SiteSettings and the current SiteSettings will be determined based on the url of the current request and injected
