### ISSUE TITLE
standardizing on guid ids - breaking changes

### ISSUE THREAD

**Issue by joeaudette** [joeaudette/cloudscribe#31]
at the moment, some model classes in cloudscribe.Core have both integer ids and guids
this was based on the design I used in mojoPortal as I have a minor goal to make a data migration path from mojoportal as low friction as possible.

I won't get long winded here about the pros/cons of integer ids vs guids, you can google that if you are interested in the topic. suffice to say that guids have advantages of not clashing when data is merged or replicated across systems (and other advantages), whereas integers in some cases can have some performance advantages.
In mojoportal my idea was to get the best of both by using integer ids for sql joins while also providing a surrogate id in the form of a guid so that if data needed to be imported or merged the guids could be used to correctly wire up the relations for new integer ids that might be needed to avoid clashes when merging data.

in cloudscribe I have arrived at a decision to remove the integer ids and strictly use guids so I will be making major changes to the model in a branch and will merge it when complete. 

However this process will be breaking for existing data and I thought I should give a heads up about that. I'm not even going to try to implement EF migrations, I'm going to just start with a new database based on the changed model.

Since this project is still in early preview I think it is reasonable to make such breaking changes which would be much more problematic to make once it is used in production. 
Sorry for the inconvenience that this may cause.

**Comment by CrispinF** [comment]
Would it be correct to think there could still be a logical migration path for any mojoPortal data, since each relevant table there had both int ID and GUID, so even where a given FK used the ID rather than the GUID it could be written across to new tables that use the GUID by doing the relevant lookups - ? Or can you see some more fundamentally breaking relationships?

**Comment by joeaudette** [comment]
yes the data will still map in very well and be possible to run queries to migrate.
but my original plan envisioned it being even easier. basically the site, users, and roles and schemaversion tables were all exactly like mojoportal so my idea was that people could insert a row into mp_SchemaVersion for cloudscribe-core 1.0.0 and then upgrade scripts would take it from there. It might still be possible to write upgrade scripts like that but I'm not promising, it would be pretty hairy scripts dropping primary keys and making a different column the primary key and hoping no errors would happen

**Comment by coe-jeubanks** [comment]
I'm definitely willing to work on creating upgrade scripts like that, at least for MySQL and/or MS SQL. As to the change itself, I think it's a better design to have a single unique key per row.

**Comment by joeaudette** [comment]
this change has been merged to the master branch, so starting with a new db will be required for those who are working with this solution

**Comment by joeaudette** [comment]
an update on this, after removing the extra keys and standardizing on guid ids, I've decided also to shorten the Id names to Id, as opposed to SiteGuid, UserGuid, RoleGuid etc, and also where previously I was using the table names from mojoPortal, I've decided that by default the table names will have a cs_ prefix instead of mp_, and table names will be singular rather than plural ie cs_Site as opposed to mp_Sites. Actually before it was inconsistent because most tables were plural but mp_Currency, mp_Language etc were singular, so I'm trying to make things more consistent.

This is another breaking change in that it will require starting with a new db after I merge these changes to the master branch.

Note that it would still be possible if someone really wanted to use different tables names or use the mojoportal table names but it would require replacing a class in in the EF Storage to different name constants and then regenerating migrations.

**Comment by joeaudette** [comment]
the id renaming is complete and merged to the master branch, so if you are using the code and you update to the latest, you will need to start with a new empty db

I "think" any other model changes going forward can be handled with migrations
