### ISSUE TITLE
Unable to resolve service for type cloudscribe.Core.IdentityServerIntegration.Services.ApiResourceManager

### ISSUE THREAD

**Issue by mdecoo** [joeaudette/cloudscribe#323]
Running in IIS Express it works. On local IIS it doesnt work. 

I have this with multiple pages
-API Resources
-API Clients
-Identity Resources

Im running Windows 10 Pro build 15603 with Dotnet Core version 2.0.3
The following lines should resolve the issue below but it doesnt. (StartupExtensions.cs in cloudscribe.Core.IdentityServerIntegration)
builder.Services.AddScoped<ApiResourceManager, ApiResourceManager>();
builder.Services.AddScoped<IdentityResourceManager, IdentityResourceManager>();
builder.Services.AddScoped<ClientsManager, ClientsManager>();

I have your latest code from github. Everything else is working.

PS, this is the first time posting something on github. Feedback is welcome to learn in this process.

```
An unhandled exception occurred while processing the request.
InvalidOperationException: Unable to resolve service for type 'cloudscribe.Core.IdentityServerIntegration.Services.ClientsManager' while attempting to activate 'cloudscribe.Core.IdentityServerIntegration.Controllers.Mvc.ClientsController'.

Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, bool isDefaultParameterRequired)
```

**Comment by joeaudette** [comment]
can you try updating to the latest nugets and let me know if it works for you now.

**Comment by mdecoo** [comment]
Hello Joe,

The following was missing:
```
         DisableIdentityServer = Configuration.GetValue<bool>("AppSettings:DisableIdentityServer");
            IdentityServerX509CertificateThumbprintName = Configuration.GetValue<string>("AppSettings:IdentityServerX509CertificateThumbprintName");
            if (!DisableIdentityServer && Environment.IsProduction())
            {
                if (string.IsNullOrEmpty(IdentityServerX509CertificateThumbprintName))
                {
                    DisableIdentityServer = true;
                }
            }
```

the appsettings should contain this information else the ID server is disabled which causes this error. 

You can close it now.
