### ISSUE TITLE
IAuthenticationService not registered.  When running VS2017 on Kestrel

### ISSUE THREAD

**Issue by MikeyUchiha** [joeaudette/cloudscribe#329]
When selecting my project from the debug drop down instead of using IIS, I get the error IAuthenticationService not registered. This is using the template for Identity Server 4 and MSSQL with no Simple Content installed.

**Comment by joeaudette** [comment]
Hi, Thanks for letting me know.
I can only guess that somehow with IIS the IAuthenticationService gets added to IServiceCollection sooner. I was able to replicate and solve the problem and I have published updated nugets.

Please update to the latest nugets and let me know if you confirm the fix.

**Comment by MikeyUchiha** [comment]
Hi Joe, it looks like it’s working. Thank you for the quick fix.
