### ISSUE TITLE
New project created with VS template fails at services.AddCloudscribeKvpUserProperties();

### ISSUE THREAD

**Issue by CrispinF** [joeaudette/cloudscribe#331]
New project created with the options below throws error on start.
![image](https://user-images.githubusercontent.com/10574730/35482751-883576fc-0431-11e8-834c-7709b4a4f693.png)
Errors:
Application startup exception: System.TypeLoadException: Method 'GetNewUserViewName' in type 'cloudscribe.UserProperties.Kvp.KvpUserInfoAdminHandler' from assembly 'cloudscribe.UserProperties.Kvp, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
at Microsoft.Extensions.DependencyInjection.StartupExtensions.AddCloudscribeKvpUserProperties(IServiceCollection services, IConfigurationRoot configuration)

**Comment by CrispinF** [comment]
And just to add, another project created without Custom Registration or IdentityServer4 integration start fine (all other settings the same).

**Comment by joeaudette** [comment]
I need to update the versions in the project template, will do that today.
In the meantime I think the error could be solved by right click solution and manage nuget packages for solution, then update all the cloudscribe nugets.

**Comment by joeaudette** [comment]
I've published updated project templates version 1.0.20 for both Visual Studio and for the dotnet new command.
I was able to reproduce the issue before the update and tested it works without error after updating the template, so will close this issue.

**Comment by CrispinF** [comment]
And just to confirm this works fine for me too, thanks.
