### ISSUE TITLE
Cloudscribe with Identity Server 4 offering PaaS

### ISSUE THREAD

**Issue by MikeyUchiha** [joeaudette/cloudscribe#336]
Hi, I was wondering how I would go about setting up the following scenario. I have an Identity Server 4 Cloudscribe project (without simple content) that I want to use to allow customers to login into their own admin sites as the Identity Server (each customer should have their own Site). There should be nothing here other than for a site admin to manage their appropriate Users. I want to be able have another Cloudscribe (MVC) multitenant project where this MVC project is the front facing view that only allows the "customer's users" to login. I would create a new Site in the MVC project for each each customer so they can view their Users here.

If you have a better recommendation for the architecture please let me know. The use case is that I want to sell Platform as a Service. Where each customer would have their own website. But it's owned and hosted by me (via Identity Server 4). They should not be able to access their own website that they can customize without logging in through Identity Server 4. I hope that helps. Thanks so much for your help and project!

**Comment by joeaudette** [comment]
Sounds pretty straightforward. 2 installations of cloudscribe, one with identityserver. Each customer backend in the identityserver installation setup with multi tenancy per customer using hostname ideally but could use folder name.

The second installation for the multi-tenant "boosting" sites one per customer. In each one you setup OpenIdConnect Authorization under Social logins configured to use the identityserver4 tenant as the backend (requires configuring the client in the identityserver4 tenant). Once the social/identityserver login is working you can check the box to "Only Use Social Logins" and then the identity server login can be used to login.

Probably the first site in each installation which is the "server admin site" should be controlled by you and the tenant sites would be created from there as child sites. Lots of details to setting it up, but definitely can be done, and there is really nothing cloudscribe specific about the identityserver4 configuration. IdentityServer4 is an openidconnect provider so it can be setup under the social logins in other cloudscribe installations as an openidconnect social login.

Relevant docs: [Identityserver Integration](https://www.cloudscribe.com/docs/identityserver-integration) and [Using Social Authentication](https://www.cloudscribe.com/docs/using-social-authentication)

**Comment by MikeyUchiha** [comment]
Thank you Joe.

**Comment by MikeyUchiha** [comment]
Hi Joe, I had a follow up question for this scenario. In the second installation of Cloudscribe that requires Open ID connection to Identity Server 4, can I still allow the Customer’s Users to login via Social through Facebook? Thanks

**Comment by joeaudette** [comment]
@MikeyUchiha yes, if the second installation uses openidconnect against the first installation with identityserver4, you can setup social auth on the identity server and when users click to login via identityserver they will see the social auth options and be able to login with them.
Alternatively you should also be able to setup social auth in addition to openid connect if you want to set them up individually for each client rather than federate them with identityserver4

**Comment by MikeyUchiha** [comment]
Joe,

Thanks for the reply. This sounds like a business decision on who we think should be tracking their Users.

Thanks
