### ISSUE TITLE
InvalidOperationException: The MetadataAddress or Authority must use HTTPS unless disabled for development by setting RequireHttpsMetadata=false.

### ISSUE THREAD

**Issue by MikeyUchiha** [joeaudette/cloudscribe#350]
I'm unable to specify an OpenID connection in Cloudscribe due to not being able to set the RequireHttpsMetadata=false.

The problem code is : 
https://github.com/joeaudette/cloudscribe/blob/d36cf2589eea8bc8421bdd2901ae8dc02d1043c4/src/cloudscribe.Core.Identity/SiteOpenIdConnectOptions.cs at Line 173.

You are throwing this error but provide no way of changing the options. Is there a way to change the authentication options?

I'm running into this issue when trying to create a second installation of Cloudscribe which uses the first installation with Cloudscribe and IdentityServer.

Thanks

**Comment by joeaudette** [comment]
@MikeyUchiha I think there are some issues to consider here.

1. should never not use https in production
2. I would not want to add a setting in the ui that would allow someone to not use https in production
3. If I were to add a config setting it would not be multi tenant aware

probably best solution is to use https in every environment including development.
You also cannot use any of the other social auth urls without https so why should openidconnect be any different, why should I add a setting in the UI that allows insecure configuration that should never be used in production?

**Comment by joeaudette** [comment]
I could possibly detect the environment is development and not require it then

**Comment by joeaudette** [comment]
I have added code to set RequireHttpsMetadata to false if the environment is development.
I've uploaded new nugets, just need to wait for them to get indexed before they will be available.

**Comment by MikeyUchiha** [comment]
Joe,

I agree that I would never not require HTTPS in a Production environment. This is purely for Development environment. I’m unable to test. Thank you for setting this to False in a Development environment.

As soon as I get home and test I will close out the Issue.

**Comment by MikeyUchiha** [comment]
Joe,
I'm getting the following error now after adding the MVC Client (Second Cloudscribe without IS4).
Unable to retrieve document from: 'http://localhost:5200/.well-known/openid-configuration

The http://localhost:5200/.well-known/openid-configuration is pointing to the First Cloudscribe with IS4. I'm not sure why but the .well-known path is missing.

**Comment by MikeyUchiha** [comment]
Joe,

I found out that the reason was because I needed to put in the IP of the Docker. However, for some reason the hybrid grant is missing. Please view this error.

IdentityServer4.Validation.AuthorizeRequestValidator:Error: Invalid grant type for client: hybrid
{
  "ClientId": "mvc",
  "ClientName": "MVC Client",
  "RedirectUri": "http://10.0.75.1:5220/signin-oidc",
  "AllowedRedirectUris": [
    "http://localhost:5220/signin-oidc",
    "http://10.0.75.1:5220/signin-oidc"
  ],
  "SubjectId": "anonymous",
  "ResponseType": "code id_token",
  "ResponseMode": "form_post",
  "GrantType": "hybrid",
  "RequestedScopes": "",
  "State": "CfDJ8NTvKtigbl1BvJYMottPKfh8Dx6olAN0y_04fvTMXFhM1qwD3zh8phneSzNk78IkSwxHgnZ7OU_ANl672z8SPHMubv9YBOOCQCvXgg6W0FZh0tHAGkTbUxhU0le95u9SUmiYRNYBV4EOvmkR79sHyXKTuY4b5wkol-aoqd_4XEcPRwpEjOBuKJEeHJekehUNh6jijZ5xDLA1B2-5YQKVYlEK_1PC4rwtJADGJJ-KYTf5NB1nta1wYbHpu0fTOq7Q08iprFaZA6fpHJwSOFqXKxqiaWmhXfDzQ4QMeORJb69SiaFSX81XfbMC9CAKm-0wmVkUGDGRc_A-4gZ2RgdWJsvyyimHsh_Uxksa4toNSNIFs_Fvd9sRMuW_pl1j3Z3ZBsW0TfjttWcvnVC_lsQSC7Q",
  "Raw": {
    "client_id": "mvc",
    "redirect_uri": "http://10.0.75.1:5220/signin-oidc",
    "response_type": "code id_token",
    "scope": "openid profile",
    "response_mode": "form_post",
    "nonce": "636553027359753746.NjczZjFhZDQtMWU3ZC00M2VhLTkxODMtZmE2YWUwMzJkY2YyZGY0MTg4ZjEtNWZmYS00NWY1LWFlYTYtZGM1YTgwMGRhZjMx",
    "state": "CfDJ8NTvKtigbl1BvJYMottPKfh8Dx6olAN0y_04fvTMXFhM1qwD3zh8phneSzNk78IkSwxHgnZ7OU_ANl672z8SPHMubv9YBOOCQCvXgg6W0FZh0tHAGkTbUxhU0le95u9SUmiYRNYBV4EOvmkR79sHyXKTuY4b5wkol-aoqd_4XEcPRwpEjOBuKJEeHJekehUNh6jijZ5xDLA1B2-5YQKVYlEK_1PC4rwtJADGJJ-KYTf5NB1nta1wYbHpu0fTOq7Q08iprFaZA6fpHJwSOFqXKxqiaWmhXfDzQ4QMeORJb69SiaFSX81XfbMC9CAKm-0wmVkUGDGRc_A-4gZ2RgdWJsvyyimHsh_Uxksa4toNSNIFs_Fvd9sRMuW_pl1j3Z3ZBsW0TfjttWcvnVC_lsQSC7Q",
    "x-client-SKU": "ID_NET",
    "x-client-ver": "2.1.4.0"
  }
}

I am also able to see that this is correct in the .wellknown/openid-configuration as provided here.

{
issuer: "http://localhost:5200",
jwks_uri: "http://localhost:5200/.well-known/openid-configuration/jwks",
authorization_endpoint: "http://localhost:5200/connect/authorize",
token_endpoint: "http://localhost:5200/connect/token",
userinfo_endpoint: "http://localhost:5200/connect/userinfo",
end_session_endpoint: "http://localhost:5200/connect/endsession",
check_session_iframe: "http://localhost:5200/connect/checksession",
revocation_endpoint: "http://localhost:5200/connect/revocation",
introspection_endpoint: "http://localhost:5200/connect/introspect",
frontchannel_logout_supported: true,
frontchannel_logout_session_supported: true,
backchannel_logout_supported: true,
backchannel_logout_session_supported: true,
scopes_supported: [
"openid",
"profile",
"email",
"orders",
"basket",
"offline_access"
],
claims_supported: [
"sub",
"updated_at",
"locale",
"zoneinfo",
"birthdate",
"gender",
"website",
"picture",
"preferred_username",
"nickname",
"middle_name",
"given_name",
"family_name",
"name",
"profile",
"email",
"email_verified"
],
grant_types_supported: [
"authorization_code",
"client_credentials",
"refresh_token",
"implicit",
"password"
],
response_types_supported: [
"code",
"token",
"id_token",
"id_token token",
"code id_token",
"code token",
"code id_token token"
],
response_modes_supported: [
"form_post",
"query",
"fragment"
],
token_endpoint_auth_methods_supported: [
"client_secret_basic",
"client_secret_post"
],
subject_types_supported: [
"public"
],
id_token_signing_alg_values_supported: [
"RS256"
],
code_challenge_methods_supported: [
"plain",
"S256"
]
}

Did you remove the hybrid grant type by accident?

**Comment by MikeyUchiha** [comment]
Nevermind,

Even though it doesn't show up in the Discovery document I was still able to add the hybrid as the Grant Type in the Client on the Identity Server 4. I'm now able to login internally using the Open ID Connect.
