### ISSUE TITLE
Date of Birth on Register page doesn't pop up Calendar

### ISSUE THREAD

**Issue by MikeyUchiha** [joeaudette/cloudscribe#353]
The Date of Birth field on the Register page doesn't pop up the Calendar, but it does pop up correctly in the Admin page when editing a User.

**Comment by joeaudette** [comment]
You need to override the RegistrationScriptsPartial.cshtml to add the needed js and you need to override RegistrationStylePartial.cshtml to add the needed css for datepicker

**Comment by joeaudette** [comment]
By default views are embedded resources form nuget packages, to override any view you need to copy it local from the github repo, the ones you need are [here](https://github.com/joeaudette/cloudscribe/tree/master/src/cloudscribe.Core.Web.Views.Bootstrap3/Views/Account)

See also https://www.cloudscribe.com/docs/themes-and-web-design

**Comment by MikeyUchiha** [comment]
Understood! I think that you should have the Date Picker in the Nuget package by default since they’re very common and you already have it working in the Admin section so it makes sense to keep a consistent experience across the whole framework.

**Comment by MikeyUchiha** [comment]
@joeaudette Can you add the Date Picker in the default Nuget package since it's common functionality?

**Comment by joeaudette** [comment]
@MikeyUchiha I will add it to the default RegistrationScriptsPartial and style partial next time I publish the nuget for views. I have some other work in progress that I need to finish before I can do that. I'm about to be travelling from Sunday through Thursday so it will likely be after I get back before I can do that.

The  script and css is in the cloudscribe.Web.Common nuget package, it just isn't currently included in the registration page by default

To solve the problem immediately you can override the RegistrationScriptsPartial.cshtml and add:

    @{ await Html.RenderPartialAsync("_DatePickerScriptsPartial"); }

and override the RegistrationStylePartial.cshtml and add:

    @{ await Html.RenderPartialAsync("_DatePickerCssPartial"); }

**Comment by MikeyUchiha** [comment]
Alright. Will do. Thank you.

**Comment by joeaudette** [comment]
I have published updated nugets and included the datepicker script and css by default on registration
