### ISSUE TITLE
TackUserIpAddress Exception

### ISSUE THREAD

**Issue by raquelcesar** [joeaudette/cloudscribe#36]
When I view the example.WebApp in the browser everything seems ok. However when I try to login, using the admin credentials, the browser just shows a blank page.
Debugging the project, I found the problem resides in the code:

`IPAddress ipv4 = context.Connection.RemoteIpAddress.MapToIPv4();`

in file `IpAddressTracker.cs`. This line of code fails because context.Connection.RemoteIpAddress is null.

Edit: Apparently, it's a bug in dnx RC1: https://github.com/aspnet/IISIntegration/issues/17

**Comment by joeaudette** [comment]
I have added some guard checks for null, so if you get the latest code this should be fixed.

I don't understand why this caused a problem for you, that code was already inside a try catch and it has not caused any problems for me. But I think it is best to avoid exceptions that can be avoided and it is better to check for null there, so thanks for letting me know.

Please let me know if these changes fixed the problem for you, and if so you can close this issue.

Thanks,

Joe

**Comment by raquelcesar** [comment]
Thank you for the quick reply.

Yes, problem is solved now, I can login with no problems.

I'm closing the issue.
