### ISSUE TITLE
User role management

### ISSUE THREAD

**Issue by StewartBellamy** [joeaudette/cloudscribe#367]
It would be useful to be able to see and manage a users roles in one place.  Also, is there way to configure what role(s) a user is added to when they register and are approved?
.

**Comment by joeaudette** [comment]
That is good feedback. I will add visibility of user roles to the manage user page.

There is currently a way to configure the default roles added to a user, probably not the best place for it but it is a property on MultiTenantOptions that can be set from appsettings.json, and is mentioned in the documentation [here](https://www.cloudscribe.com/docs/multi-tenant-support).

It really isn't related to multi-tenancy and I think  we should refactor and move that elsewhere and update the documentation. I will do that at the same time as adding visibility to all user roles so it can be tracked on this issue, but for now it can be done with the MultiTenantOptions.DefaultNewUserRoles

**Comment by joeaudette** [comment]
Role visibility has now been surfaced on the user management page, and user roles can also be deleted from there. Roles can still only be added from role management section.

Default roles configuration has been removed from MultiTenantOptions to NewUserOptions and can be specified from config like this:

      "NewUserOptions": {
        "DefaultNewUserRoles": "Authenticated Users"
      }

shown above with default value, you can add multiple roles with semi colon separator
