### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by mikeandersun** [joeaudette/cloudscribe#39]
I Clone the master branch, these are the build errors :
```
  Unable to resolve 'cloudscribe.Logging.EF (>= 1.0.0)' for '.NETCoreApp,Version=v1.0'.
  Unable to resolve 'cloudscribe.Logging.Web (>= 1.0.0)' for '.NETCoreApp,Version=v1.0'.
  Unable to resolve 'cloudscribe.Web.Navigation (>= 1.0.1)' for '.NETCoreApp,Version=v1.0'.
  Unable to resolve 'cloudscribe.Web.Pagination (>= 1.0.1)' for '.NETCoreApp,Version=v1.0'.
  Unable to resolve 'NoDb (>= 1.0.0)' for '.NETCoreApp,Version=v1.0'.
```
It seams some of projects build with `netstandard1.5` and some build with `netstandard1.0`.

**Comment by joeaudette** [comment]
did you install rc2 and tooling from [http://dot.net](http://dot.net)?

did you try open the command terminal in the folder with cloudscribe.sln and run the command?

    dotnet restore --no-cache

**Comment by mikeandersun** [comment]
I install `DotNetCore.1.0.0.RC2-VS2015Tools.Preview1.exe` and  `NuGet.Tools`(NuGet 3.5) and run `dotnet restore --no-cache` command. 
I have others RC2 projects that use  `cloudscribe.Web.Pagination` packages and work fine.

**Comment by joeaudette** [comment]
I don't know what to tell you, it works fine on my machine and I know of others who have also used it with no errors. I only installed DotNetCore I did not install NuGet separately, maybe something is messed up with your NuGet feeds

**Comment by mikeandersun** [comment]
You were right.
NuGet Config files used:

`C:\Users\mike\AppData\Roaming\NuGet\NuGet.Config C:\ProgramData\nuget\Config\Microsoft.VisualStudio.Offline.config`


I don't know why some of your packages don't pull from this feeds!. 
I add `NuGet.Config` to the root of the project and it work. 
I think it is better to have `NuGet.config` in the root of the project to override feeds.
