### ISSUE TITLE
js ,css and image files per tenant

### ISSUE THREAD

**Issue by mikeandersun** [joeaudette/cloudscribe#40]
I needs to have js ,css and image files per tenant. It is possible?

**Comment by joeaudette** [comment]
yes you can have different themes per tenant and you can control js, css, images and other style from the theme. You can override any view by copying it into the theme folder keeping the folder same structure as it was under the Views folder

currently themes are stored under

    /tenantfiles/[aliasid]/themes/[themename]

I think I will be renaming the tenantfiles folder to sitefiles to use consistent terminology, ie I mostly refer to sites but some places call them tenants, they are the same thing but I should be consistent in the terminology so will probably change that.

aliasid is a property of SiteSettings that I added after removing the integer SiteId, its purpose is to provide a friendlier identifier vs Id which is a guid, if AliasId is empty it will use the guid id for the folder name. currently there is no logic to make sure AliasId is unique per site but I plan to implement validation for that. currently if left blank when creating a site it will use the count of sites plus 1 to make an aliasid like tenant-1, tenant-2 but again I plan to change the tenant terminology to "site"

so ultimately any view that adds css or js to the page can be override from the theme, note how the layout files have optional sections where child views can add css or js or meta data

    @RenderSection("Meta", required: false)
    @RenderSection("Styles", required: false)
    @RenderSection("Bottom", required: false)
    @RenderSection("scripts", required: false)

many things are still subject to change in this project

**Comment by mikeandersun** [comment]
@joeaudette  thanks . So we will have `sitefolder `as an alternative for `wwwroot` for the site(tenant)?
My plan is to have many static files(js, css,sass ,images and html) per site that can manage via a file manager. I hope can achieve this with your magic projects.

**Comment by joeaudette** [comment]
no, static files can only be served from below wwwroot I have no plans or goals to try to override or change that in this project
you can organize files as you wish below wwwroot

**Comment by joeaudette** [comment]
cloudscribe core is not a content system

it may be possible for you to implement your own file manager and perhaps virtualpathprovider to serve and manage files from outside wwwroot, but that is not something I'm trying to provide with this project

**Comment by mikeandersun** [comment]
Can we develop a content system on `cloudscribe`? Is the any restrictions?

**Comment by joeaudette** [comment]
what do you mean restrictions, it is licensed as apache 2, you can build whatever you like on top of it. I plan to make it possible to use my cloudscribe.SimpleContent features with cloudscribe.Core, but that doesn't mean I'm planning to serve static files from outside wwwroot

there are notes in the asp.net docs for [how to manage static files or serve them from another location](https://docs.asp.net/en/latest/fundamentals/static-files.html)

but serving files from a different location per tenant would be more complex, and would involve resolving the the tenant for static file requests which I do not want to do for performance reasons

also the main benefit of the new wwwroot folder is for security reasons to separate static files from code, once you start serving files from elsewhere you increase the surface area of security concerns
there is good security benefit if the only files that can be retrieved directly by http requests are limited to wwwroot folder. I'm also glad that web.config no longer lives in wwwroot folder in rc2

**Comment by mikeandersun** [comment]
I think  

> resolving the the tenant for static file requests

is what i looking for. But I try your solution 

> organize files as you wish below wwwroot

**Comment by joeaudette** [comment]
just some additional thoughts and ideas about this

currently we have the static file middleware runs first, which is best for performance, we don't have to resolve the tenant for static file requests nor do those requests need to be processed by middleware that runs later in the pipeline, so the startup code is like this:

          app.UseStaticFiles();
            app.UseSession();
            app.UseMultitenancy<cloudscribe.Core.Models.SiteSettings>();
            var multiTenantOptions = multiTenantOptionsAccessor.Value;

            app.UsePerTenant<cloudscribe.Core.Models.SiteSettings>((ctx, builder) =>
            {
			   // tenant specific cookie middleware goes here
			    ...
	     }

but if you really wanted to you could change the order of middleware and maybe run separate static file middleware per tenant, I don't know if it would work but the idea would be like this:

    //app.UseStaticFiles();
      app.UseSession();
       app.UseMultitenancy<cloudscribe.Core.Models.SiteSettings>();
        var multiTenantOptions = multiTenantOptionsAccessor.Value;

        app.UsePerTenant<cloudscribe.Core.Models.SiteSettings>((ctx, builder) =>
        {
	      builder.UseStaticFiles(new StaticFileOptions()
	       {
		     FileProvider = new PhysicalFileProvider(@"c:\some\tenant\specific\folder"),
		      RequestPath = new PathString("/tenant2")
		 });
				  
	         // tenant specific cookie middleware goes here
	          ...
	}

you could experiment with the idea and find out if it could work. but I do think there would be some performance loss compared to running a single static file middleware early in the pipeline

**Comment by joeaudette** [comment]
per tenant static files and per theme static files are now implemented
https://github.com/joeaudette/cloudscribe/wiki/Customizing-Views-and-Display-Templates
