### ISSUE TITLE
Error at load solution

### ISSUE THREAD

**Issue by net4u** [joeaudette/cloudscribe#41]
Hi,

I encounter this at solution load:
![2016-05-25](https://cloud.githubusercontent.com/assets/255743/15532713/ed459d34-2269-11e6-9430-3f7b1db07308.png)
By consequence at build I get this:
![2016-05-25 1](https://cloud.githubusercontent.com/assets/255743/15532740/0bb837b8-226a-11e6-8bad-5866e27a6559.png)

I assume that I installed all net.core related. Any hints please?

**Comment by minhnhat2807** [comment]
I think you should install .NET core CLI https://github.com/dotnet/cli

**Comment by joeaudette** [comment]
did you install rc2 and tooling from [http://dot.net](http://dot.net)?

**Comment by net4u** [comment]
yes, both core and sdk, latest available

**Comment by net4u** [comment]
anyway at first sight it seems very unfamiliar for me asp.core (just finished to learn mvc :-( )

**Comment by joeaudette** [comment]
did you have any previous versions of asp.net core installed? Seems like something didn't install correctly on your machine.

I would check under Help > About in VS 2015 to first make sure you have the right stuff there, ie VS 2015 update 2 should be installed before you installed .net core think. You may need to try to run the installer again. I can't really offer to support VS 2015 issues, there are better places to ask for help with that if the problem persists

![vs2015-about](https://cloud.githubusercontent.com/assets/101627/15540986/370c1478-2258-11e6-9d19-889994fa0832.png)

**Comment by net4u** [comment]
I did not noticed any errors on install. Anyway if relevant I used to uninstall VS201x earlier these days, for gaining some space.
So I have this:
//
Microsoft Visual Studio Community 2015
Version 14.0.25123.00 Update 2
Microsoft .NET Framework
Version 4.6.01038

Installed Version: Community

Visual Basic 2015   00322-20000-00000-AA915
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA915
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA915
Microsoft Visual C++ 2015

Visual F# 2015   00322-20000-00000-AA915
Microsoft Visual F# 2015

Windows Phone SDK 8.0 - ENU   00322-20000-00000-AA915
Windows Phone SDK 8.0 - ENU

Application Insights Tools for Visual Studio Package   5.206.60517.2
Application Insights Tools for Visual Studio

ASP.NET AJAX Control Toolkit   1.0
ASP.NET AJAX Control Toolkit Visual Studio integration package

ASP.NET and Web Tools 2015.1   14.1.20512.0
ASP.NET and Web Tools 2015.1

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.9   14.0.20316.0
Azure App Service Tools v2.9

Common Azure Tools   1.7
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

DataFactoryProject   1.0
Microsoft Data Factory Package

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JustDecompile Tools   1.0
Makes JustDecompile functionality available in VIsual Studio. Requires JustDecompile installation.

Microsoft .NET Core Tools (Preview 1)   14.1.20512.0
Microsoft .NET Core Tools (Preview 1)

Microsoft Azure Data Factory Node Node   1.0
Azure Data Factory extension for Visual Studio Server Explorer.

Microsoft Azure HDInsight HQL Service   2.0.6000.0
Language service for Hive query

Microsoft Azure HDInsight Tools for Visual Studio   2.0.6000.0
An integrated development environment for HDInsight application development.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.7
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.7.30818.1601

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.9.40323.3

Microsoft Azure Tools   2.8
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.8.40114.1

Microsoft Azure Tools   2.5
Microsoft Azure Tools for Microsoft Visual Studio 2015 Preview - v2.5.21104.1601

NuGet Package Manager   3.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Python Tools for Visual Studio   2.2.40315.00
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

Python Tools for Visual Studio - Django Integration   2.2.40315.00
Provides templates and integration for the Django web framework.

Python Tools for Visual Studio - Profiling Support   2.2.40315.00
Profiling support for Python projects.

SQL Server Data Tools   14.0.60311.1
Microsoft SQL Server Data Tools

Syncfusion ASP.NET MVC (Mobile) Extension   13.4.0.53
Provides Project Templates to create Syncfusion ASP.NET MVC (Mobile) projects.

Syncfusion ASP.NET MVC (Web) Extension   13.4.0.53
Provides Project Templates to create Syncfusion ASP.NET MVC (Web) projects and samples.

Syncfusion Item Templates    13.4.0.53
Adds new Syncfusion items to projects with necessary base code.

TypeScript   1.8.31.0
TypeScript tools for Visual Studio

Visual C++ for Cross Platform Mobile Development   1.0
Visual C++ for Cross Platform Mobile Development

Visual Studio Tools for Apache Cordova   Update 9
Visual Studio Tools for Apache Cordova

Visual Studio Tools for Unity   2.2.0.0
Visual Studio Tools for Unity

Visual Studio Tools for Universal Windows Apps   14.0.25219.00
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Web Essentials 2015.2   2.0.214
Adds many useful features to Visual Studio for web developers. Requires Visual Studio 2015

Windows Installer XML Toolset   3.10.0.1823
Windows Installer XML Toolset version 3.10.0.1823
Copyright (c) Outercurve Foundation. All rights reserved.

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

Xamarin   4.0.4.4 (a9c7826)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   6.0.4.0 (ee215fc)
Visual Studio plugin to enable development for Xamarin.Android.

Xamarin.iOS   9.6.2.2 (be25da5)
Visual Studio extension to enable development for Xamarin.iOS.
//

**Comment by joeaudette** [comment]
what happens if you open a command prompt in the root of the solution and run the command:

    dotnet restore --no-cache

?

**Comment by net4u** [comment]
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\Laurentiu\Downloads\cloudscribe-master\cloudscribe-master>dotnet restor
e --no-cache

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or ass
embly 'Program' or one of its dependencies. The system cannot find the file spec
ified.
Restoring Tool 'Microsoft.EntityFrameworkCore.Tools' for 'C:\Users\Laurentiu\App
Data\Local\Temp\e604d29b-ab8e-4080-9545-78ed3da90291\bin\project.json' in 'C:\Us
ers\Laurentiu\AppData\Local\Temp\e604d29b-ab8e-4080-9545-78ed3da90291\bin'

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or ass
embly 'Program' or one of its dependencies. The system cannot find the file spec
ified.
Object reference not set to an instance of an object.

C:\Users\Laurentiu\Downloads\cloudscribe-master\cloudscribe-master>

**Comment by joeaudette** [comment]
do you have any custom nuget feeds configured?
what feeds are listed in VS under Tools > Options > NuGet Package Manager > Package  Sources

**Comment by net4u** [comment]
![2016-05-25 6](https://cloud.githubusercontent.com/assets/255743/15542200/694fc4ee-2298-11e6-9042-8927dd3588dd.png)

**Comment by joeaudette** [comment]
try get latest of the code again, I've removed the Sasskit project and changed back t o nuget reference for that since they just released a compatible one.
more importantly I've added a nuget.config file which should make sure it uses the correct feed, I don't know if that will solve it but worth a try

**Comment by net4u** [comment]
ok, I will try. come back in few moments

**Comment by net4u** [comment]
Huh, is the same, in every detail.

**Comment by joeaudette** [comment]
what happens if you create a new .net core web app with individual user accounts ie identity, after creating that inspect the project.json to make sure everything is netstandard/rc2
does that build and run?

**Comment by net4u** [comment]
I just try another thing: I created a new core solution from scratch. I have the same result :-(
`{
  "userSecretsId": "aspnet-WebApplication1-fd0a4f54-eea7-4588-a6d7-e39b4a4dcfa3",

  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0-rc2-3002702",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview1-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-rc2-final",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-rc2-final",
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview1-final",
      "type": "build"
    },
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc2-final",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-rc2-final",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview1-final",
      "type": "build"
    },
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
      "version": "1.0.0-preview1-final",
      "type": "build"
    }
  },

  "tools": {
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": "portable-net45+win8+dnxcore50"
    },
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": "portable-net45+win8+dnxcore50"
    },
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": [
        "portable-net45+win8+dnxcore50",
        "portable-net45+win8"
      ]
    },
    "Microsoft.Extensions.SecretManager.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": "portable-net45+win8+dnxcore50"
    },
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": [
        "portable-net45+win8+dnxcore50",
        "portable-net45+win8"
      ]
    }
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "gcServer": true
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
`

**Comment by joeaudette** [comment]
one thing I noticed different on your machine was in your vs info:

    Microsoft .NET Framework
Version 4.6.01038

on my machine I have:

    Microsoft .NET Framework
Version 4.6.01055

I would try again install rc2 and tooling from http://dot.net

**Comment by joeaudette** [comment]
make sure you choose .NET Core from there

**Comment by net4u** [comment]
I am sure that I have installed the latest core from there. I will try tomorrow to uninstall VS and I hope also all related to asp.net (but I am not sure about that, it will be some mess after this)

**Comment by ariesdane** [comment]
@net4u.

I had a developer with the same problem today. He was installing the correct RC2 components, but kept getting that same error. Ended up he had an old dotnet beta client tool that was mucking things up. 

To see if you have that same problem, pull up a command prompt and type 

`dotnet --version. `

If the version contains "beta", then bingo - you found your problem, because it should read 1.0.0-preview1-002702 as of the time of this post.

To get rid of the old beta tool, simply go to add / remove programs and uninstall it. It won't be listed next to the new .Net Core runtimes. Rather, it's hiding somewhere with all the other older .Net stuff. 

Once my dev uninstalled it everything immediately started working.

Happy hunting.

**Comment by net4u** [comment]
It reports strange things:
//
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\Laurentiu>dotnet --version
.NET Command Line Tools (1.0.0)
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64

C:\Users\Laurentiu>
//
