### ISSUE TITLE
Per tenant database.

### ISSUE THREAD

**Issue by mikeandersun** [joeaudette/cloudscribe#42]
Is is possible to have per tenant database?
With `saaskit `we have a database for any tenant.

**Comment by joeaudette** [comment]
yes, I'm pretty sure that is what @BenFoster, the author of SaasKit does. I'm pretty sure I could get that working with regular aspnetcore identity, and pretty sure I could get that working with cloudscribe.Core.

to do that in addition to per tenant middleware there would need to be setup some per tenant dependencies to inject different dbcontext with different connection string per tenant. Saaskit has a [library for doing that with structuremap](https://github.com/saaskit/saaskit/tree/master/src/SaasKit.Multitenancy.StructureMap)

it would also require some kind of list of tenants with their connection strings which could be simply created from config or it could be done with another common database

right now I have a lot to do that I have been waiting for rc2 for nuget packaging and localization, once those things are done I plan to create samples of different scenarios and I will try to make one with per tenant database
