### ISSUE TITLE
Error during run.

### ISSUE THREAD

**Issue by mikeandersun** [joeaudette/cloudscribe#47]
```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has
been thrown by the target of an invocation. ---> System.AggregateException: One
or more errors occurred. (Column 'Code' in table 'cs_Currency' is of a type that
 is invalid for use as a key column in an index.) ---> System.Data.SqlClient.Sql
Exception: Column 'Code' in table 'cs_Currency' is of a type that is invalid for
 use as a key column in an index.
```

**Comment by joeaudette** [comment]
the currency model and table were removed, you may need to try with a clean db
also everything is updated to RTM so [make sure you have vs 2015 update 3 and new tooling](https://github.com/joeaudette/cloudscribe/wiki/Working-with-the-source-Code)

**Comment by mikeandersun** [comment]
Yes. I updated my dev environment  to RTM , and provide new database in the connection string. The Db created but no any tables in it!

**Comment by joeaudette** [comment]
thanks for letting me know, I was able to replicate the problem with a new db. I regenerated the migration and then found some other errors that needed fixing due to model changes. I've pushed the changes so it should be working now with a new db

**Comment by mikeandersun** [comment]
Worked fine. Thanks for quick push :+1:
