### ISSUE TITLE
How to start working to have a content management system ?

### ISSUE THREAD

**Issue by mikeandersun** [joeaudette/cloudscribe#6]
I interested to have a simple CMS , can you point me some starting point?

**Comment by joeaudette** [comment]
I'm not the wizard of oz please don't ask silly open ended questions

**Comment by mikeandersun** [comment]
Sorry, Can you please delete this issue. :(

**Comment by joeaudette** [comment]
sorry, I would be happy to but there doesn't seem to be a feature for deleting issues on github
