### ISSUE TITLE
per tenant layout?

### ISSUE THREAD

**Issue by joeaudette** [joeaudette/cloudscribe#7]
currently all the tenants use View/Shared/_Layout.cshtml, it should be possible to use different layouts per tenant.

This is a planned feature not yet implemented.

**Comment by mikeandersun** [comment]
issue https://github.com/joeaudette/cloudscribe/issues/5

**Comment by joeaudette** [comment]
@mikeandersun I guessed that might be what you were asking about in issue#5 but it was not clear.

**Comment by joeaudette** [comment]
fyi I did some work on this today and implemented a convention approach where it will try to find a layout named Site1Layout.cshtml or Site2Layout.cshtml etc using the site id,if not found it falls back to using _Layout.cshtml

I also implemented an approach where the layout name can be stored in the mp_Sites table in the Skin field but there is currently no UI to select a layout or save it's name in that field so the only way to use that right now is to manually enter it in the database. 

a simple configuration change can be used to determine which approach is used, LayoutSelectorOptions is wired up from startup

You can see in _ViewStart.cshtml it looks like this:

    @inject ILayoutSelector layoutSelector
    @{  
        Layout = layoutSelector.GetLayoutName(ViewContext);
    }

and the ILayoutSelector that is configured by DI is this new TenantLayoutSelector.cs

https://github.com/joeaudette/cloudscribe/blob/master/src/cloudscribe-core/src/cloudscribe.Core.Web/Razor/TenantLayoutSelector.cs

it is still a work in progress and may change but it is working

**Comment by joeaudette** [comment]
fyi there is now a dropdown list in site settings to choose a layout file. By naming conventions the list is filtered so that it is possible to prevent different tenants from selecting layouts that belong to another tenant. If there exist no layout files named with the site id it will fallback to using Default_Layout.cshtml. Tenant specific layouts can be created by naming them like Site2_somename_Layout.cshtml. The display name of the template is filtered to just "somename" in this case. I have created a few layouts for sites 1 and 2 with different bootstrap themes I foundon bootswatch.com, but the vertical menu style for them needs work I guess because those themes don't have anything for metismenu.

**Comment by joeaudette** [comment]
I have implemented this feature and documented it in the wiki 
https://github.com/joeaudette/cloudscribe/wiki/Customizing-Views-and-Display-Templates

Therefore I am closing this issue.

**Comment by mikeandersun** [comment]
[This enhancement](https://github.com/aspnet/Mvc/issues/3307) may be useful.
